"""Crear tablas de roles, usuarios, módulos y permisos

Revision ID: 41aeeb7f8a61
Revises: 
Create Date: 2025-01-29 00:25:43.588729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aeeb7f8a61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['Rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('UsuarioModulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('privilegio', sa.Enum('lectura', 'admin'), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['Modulo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsuarioModulo')
    op.drop_table('Usuario')
    op.drop_table('Rol')
    op.drop_table('Modulo')
    # ### end Alembic commands ###
