"""Actualizar relaciones Modulo y Seccion

Revision ID: 55172aaf14b6
Revises: d36cad218229
Create Date: 2025-01-31 02:33:33.554475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55172aaf14b6'
down_revision = 'd36cad218229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seccion', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seccion', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    # ### end Alembic commands ###
